### ISSUE TITLE
get training data

### ISSUE THREAD

**Issue by QianwenZhu** [Ourshanabi/Burst-denoising#1]
Do you know where could I download the training dataset ?  
Thanks in advance.

**Comment by fuaiguo** [comment]
Hello, first of all, thank you very much for your code.Since many functions in the code are not called, especially the relevant processing of adding noise, could you please provide the calling code generated by adding noise data?thank you

**Comment by RaymZhang** [comment]
The code to reproduce the training database for the bursts is available here: https://github.com/cmla/f16-video-set

**Comment by RaymZhang** [comment]
The noise is added each time an image is loaded into a batch during training time. The important part for the code is in Burstload.py or ImagesloaderRAM.py that are modified version of the original pytorch dataloader.
